### 📌 Day 2 — NumPy Indexing, Slicing & Broadcasting (Code)

In [11]:
import numpy as np

##### 1. Indexing (selecting elements)

In [12]:
arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)

print("\nFirst element:", arr[0])
print("Last element:", arr[-1])
print("Middle element:", arr[2])

Array: [10 20 30 40 50]

First element: 10
Last element: 50
Middle element: 30


##### 2D array indexing

In [13]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

print("\n2D Array:\n", arr2)
print("Element at row 0, col 1:", arr2[0, 1])
print("Element at row 2, col 2:", arr2[2, 2]) 


2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 0, col 1: 2
Element at row 2, col 2: 9


##### 2. Slicing (selecting ranges)

In [14]:
arr3 = np.array([5, 10, 15, 20, 25, 30])

print("\nSlice 1 (0:3):", arr3[0:3])
print("Slice 2 (2:5):", arr3[2:5])
print("Slice 3 (start to 4):", arr3[:4])
print("Slice 4 (3 to end):", arr3[3:])

# 2D slicing
print("\n2D Slice (first 2 rows, first 2 cols):\n", arr2[:2, :2])
print("\n2D Slice (rows 1-2, all cols):\n", arr2[1:, :])


Slice 1 (0:3): [ 5 10 15]
Slice 2 (2:5): [15 20 25]
Slice 3 (start to 4): [ 5 10 15 20]
Slice 4 (3 to end): [20 25 30]

2D Slice (first 2 rows, first 2 cols):
 [[1 2]
 [4 5]]

2D Slice (rows 1-2, all cols):
 [[4 5 6]
 [7 8 9]]


##### 3. Boolean Indexing

In [15]:
arr4 = np.array([10, 25, 30, 45, 50])

print("\nValues > 30:", arr4[arr4 > 30])
print("Values even:", arr4[arr4 % 2 == 0])


Values > 30: [45 50]
Values even: [10 30 50]


##### 4. Broadcasting

In [16]:
x = np.array([1, 2, 3, 4])
print("\nOriginal x:", x)

print("Add 5 to each value:", x + 5)
print("Multiply each value by 2:", x * 2)

# Broadcasting with 2D array
mat = np.array([[1, 2, 3],
                [4, 5, 6]])

print("\nMatrix:\n", mat)
print("Add array [10, 20, 30]:\n", mat + np.array([10, 20, 30]))


Original x: [1 2 3 4]
Add 5 to each value: [6 7 8 9]
Multiply each value by 2: [2 4 6 8]

Matrix:
 [[1 2 3]
 [4 5 6]]
Add array [10, 20, 30]:
 [[11 22 33]
 [14 25 36]]
