#### 📌Day 1 — NumPy Basics

In [20]:
import numpy as np

##### 1. Creating basic NumPy arrays

In [21]:
# 1D array
arr1 = np.array([1, 2, 3, 4])
print("1D Array:", arr1)

1D Array: [1 2 3 4]


In [22]:
# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2)


2D Array:
 [[1 2 3]
 [4 5 6]]


##### 2. Checking array properties

In [23]:
print("\nShape:", arr2.shape)
print("Data Type:", arr1.dtype)
print("Number of Dimensions:", arr1.ndim)
print("Size (total elements):", arr1.size)


Shape: (2, 3)
Data Type: int64
Number of Dimensions: 1
Size (total elements): 4


##### 3. Creating arrays using NumPy functions

In [24]:
zeros_arr = np.zeros((3, 3))
print("\nArray of zeros:\n", zeros_arr)


Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
ones_arr = np.ones((3, 4))
print("\nArray of ones:\n", ones_arr)


Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
range_arr = np.arange(0, 10, 2)
print("\nArray with range:\n", range_arr)


Array with range:
 [0 2 4 6 8]


In [27]:
lin_arr = np.linspace(0, 1, 5)
print("\nArray with linspace:\n", lin_arr)


Array with linspace:
 [0.   0.25 0.5  0.75 1.  ]


##### 4. Basic NumPy operations

In [28]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("\nAddition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)



Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


##### 5. Useful Math Functions

In [29]:
print("\nMean:", np.mean(a))
print("Max:", np.max(a))
print("Min:", np.min(a))
print("Square Root:", np.sqrt(a))
print("Sum:", np.sum(a))


Mean: 20.0
Max: 30
Min: 10
Square Root: [3.16227766 4.47213595 5.47722558]
Sum: 60
