### Day 4 — NumPy Matrix Operations & Linear Algebra (Code)

In [18]:
import numpy as np

##### 1. Creating Matrices (2D Arrays)

In [19]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7, 8, 9],
              [1, 2, 3]])

print("Matrix A:\n", a)
print("\nMatrix B:\n", b)

Matrix A:
 [[1 2 3]
 [4 5 6]]

Matrix B:
 [[7 8 9]
 [1 2 3]]


##### 2. Basic Matrix Operations

In [20]:
print("\nMatrix Addition:\n", a + b)
print("\nMatrix Subtraction:\n", a - b)
print("\nMatrix Multiplication (Element-wise):\n", a * b)


Matrix Addition:
 [[ 8 10 12]
 [ 5  7  9]]

Matrix Subtraction:
 [[-6 -6 -6]
 [ 3  3  3]]

Matrix Multiplication (Element-wise):
 [[ 7 16 27]
 [ 4 10 18]]


##### 3. Dot Product

In [21]:

C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

D = np.array([[1, 2, 3],
              [4, 5, 6]])

print("\nMatrix C:\n", C)
print("\nMatrix D:\n", D)

dot_product = np.dot(C, D)
print("\nDot Product (C x D):\n", dot_product)


Matrix C:
 [[1 2]
 [3 4]
 [5 6]]

Matrix D:
 [[1 2 3]
 [4 5 6]]

Dot Product (C x D):
 [[ 9 12 15]
 [19 26 33]
 [29 40 51]]


##### 4. Matrix Transpose

In [22]:
print("\nTranspose of A:\n", a.T)
print("\nTranspose of C:\n", b.T)


Transpose of A:
 [[1 4]
 [2 5]
 [3 6]]

Transpose of C:
 [[7 1]
 [8 2]
 [9 3]]


##### 5. Linear Algebra Functions

In [23]:
square_matrix = np.array([[4, 2],
                          [3, 1]])

print("\nSquare Matrix:\n", square_matrix)


Square Matrix:
 [[4 2]
 [3 1]]


In [24]:
# Determinant
det = np.linalg.det(square_matrix)
print("\nDeterminant:", det)


Determinant: -2.0


In [25]:
inv = np.linalg.inv(square_matrix)
print("Inverse:\n", inv)

Inverse:
 [[-0.5  1. ]
 [ 1.5 -2. ]]


In [26]:
# Eigenvalues & Eigenvectors
eigen_vals, eigen_vecs = np.linalg.eig(square_matrix)
print("\nEigenvalues:", eigen_vals)
print("Eigenvectors:\n", eigen_vecs)


Eigenvalues: [ 5.37228132 -0.37228132]
Eigenvectors:
 [[ 0.82456484 -0.41597356]
 [ 0.56576746  0.90937671]]


##### 6. Solving Linear Equations
##### Example: 2x + 3y = 9, 4x + y = 13


In [27]:
coeff_matrix = np.array([[2, 3],
                         [4, 1]])

constants = np.array([9, 13])

solution = np.linalg.solve(coeff_matrix, constants)
print("\nSolution of linear equations (x, y):", solution)


Solution of linear equations (x, y): [3. 1.]
